apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elastalert-k8s
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: elastalert-k8s
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elastalert-k8s
    spec:
      volumes:
      - name: config-dir
        emptyDir: {}
      - name: admin-config
        configMap:
          name: ea-config
      - name: user-rules-dir
        emptyDir: {}
      containers:
      - image: rvadim/elastalert-k8s-automation:latest
        imagePullPolicy: Always
        name: elastalert-k8s
        env:
          - name: CONFIG
            value: /config/admin/config.yaml
        volumeMounts:
        - mountPath: /config
          name: config-dir

        - mountPath: /config/admin
          name: admin-config

        - mountPath: /config/rules
          name: user-rules-dir

      - image: rvadim/elastalert-k8s-automation:elastalert-latest
        imagePullPolicy: IfNotPresent
        name: elastalert
        volumeMounts:
        - mountPath: /config
          name: config-dir
        command:
          - python
          - -m
          - elastalert.elastalert
          - --config
          - /config/config.yaml
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ea-config
data:
  config.yaml: |
    es_host: 127.0.0.1
    es_port: 9200
    es_password: "1234"

    rules_folder: /config/rules

    buffer_time:
        minutes: 15
        seconds: 30

    writeback_index: elastalert_status

    run_every:
        seconds: 30

