apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elastalert-k8s
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: elastalert-k8s
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elastalert-k8s
    spec:
      containers:
      - image: dkondyrev/elastalert-k8s-automation:latest
        imagePullPolicy: IfNotPresent
        name: elastalert-k8s