FROM python:3.7


LABEL version="0.0.1"
LABEL repository="https://github.com/rvadim/elastalert-k8s-automation"
LABEL homepage="https://github.com/rvadim/elastalert-k8s-automation"
LABEL maintainer="vadim.reyder <vadim.reyder@gmail.com>"
LABEL com.github.actions.name="GitHub Action for tox"
LABEL com.github.actions.description="Action that enables testing of python 3.6 apps with tox" 

RUN pip install tox
